vaadin.launch-browser=true
spring.application.name=catshelter

spring.datasource.url=jdbc:h2:mem:catshelter;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Admin notifications
app.admin.email=admin@catshelter.fi
app.base-url=http://localhost:8080

spring.security.oauth2.client.registration.github.client-id=Ov23liNCGkpOpNBForeA
spring.security.oauth2.client.registration.github.client-secret=53ef3dac980a7af2111ea42a5385235bcdbbeca3