spring.application.name=catshelter

spring.datasource.url=jdbc:postgresql://db:5432/catshelter
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=catshelter
spring.datasource.password=catshelter

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.h2.console.enabled=false
vaadin.launch-browser=false
